### PR TITLE
feat(non-compose-accessors): add non compose accessors

### PR DESCRIPTION
**Pull request by humblerookie**
Sometimes we may need to access strings beyond the compose framework. 

This PR makes it easy to use it if needed. Resolves https://github.com/adrielcafe/lyricist/issues/38

Do let me know what you think of it.

### CODE REVIEW

**Comment by humblerookie** [comment]
@prof18  It would be nice if you could take a look at this.

**Comment by humblerookie** [comment]
@DevNatan  It would be nice if you could take a look at this.

**Comment by CodeIdeal** [comment]
I suggest providing a property delegate method similar to strings for accessing outside of Compose scopes, which would be more convenient.

Like this:
https://github.com/CodeIdeal/lyricist/blob/0eefc3f5db271cc93699245aba880c3ebd26ebf3/lyricist-processor-compose/src/main/java/cafe/adriel/lyricist/processor/internal/LyricistSymbolProcessor.kt#L65-L73 #

**Comment by humblerookie** [comment]
@CodeIdeal  This wouldn't allow accessing other locales than the default one.

**Comment by humblerookie** [comment]
@adrielcafe @DevNatan Just wondering if anything more needs to be done on this, it would be nice to get some feedback on this PR.

**Comment by DevNatan** [comment]
Well done! THX @humblerookie 🙏🏽🙏🏽

**Comment by nabeelahamedk** [comment]
@DevNatan, @adrielcafe Is this available in 1.7.0 release?

**Pull request merged**
